✨(typed-value): Add string constructor for TypedBigDecimal
team-kaba/selidor pull request #225
Opened 2020-11-11 01:56 UTC by nagashima-toru

* Added constructor to generate TypedBigDecimal from String

2020-11-11 03:13 UTC, ryotan requested changes

2020-11-11 03:13 UTC, ryotan commented on selidor-projects/selidor-libraries/selidor-typed-value-mapstruct/src/main/java/pw/itr0/selidor/type/mapstruct/util/TypedBigDecimalTranslator.java
> +    return value.toPlainString();
```suggestion
    return value == null ? null : value.toPlainString();
```

2020-11-11 03:13 UTC, ryotan commented on selidor-projects/selidor-libraries/selidor-typed-value/src/main/java/pw/itr0/selidor/type/TypedBigDecimal.java
> +  protected TypedBigDecimal(String value, boolean nullFirst) {
ここでコンストラクタ定義しておかなくても、実装クラス側でコンストラクタを足せばよさそうな気がしてきました。
Translatorでの変換はできるので、割と大丈夫そうな気がします。

2020-11-11 23:36 UTC, nagashima-toru commented on selidor-projects/selidor-libraries/selidor-typed-value/src/main/java/pw/itr0/selidor/type/TypedBigDecimal.java
> +  protected TypedBigDecimal(String value, boolean nullFirst) {
確かにそうだね。
このコンストラクタは消しておきます。

2020-11-12 01:35 UTC, ryotan approved these changes

2020-11-12 01:35 UTC, merged